services:
  price-sync-bot:
    build:
      context: .
      args:
        - PROXY_URL
    container_name: price-sync-bot
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./logs:/app/logs
      - ./reports:/app/reports
      - ./price_files:/app/price_files
    environment:
      - TZ=Europe/Moscow

  price-b24-bot:
    build:
      context: .
      args:
        - PROXY_URL
    container_name: price-b24-bot
    restart: unless-stopped
    env_file: .env
    entrypoint: ["python", "-m", "bitrix24_bot.main"]
    ports:
      - "7778:7778"
    volumes:
      - ./logs:/app/logs
    environment:
      - TZ=Europe/Moscow
